// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var John = require("./John.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Channel = require("./Channel.bs.js");

function end$prime(param) {
  
}

function filter(source, pred) {
  console.log("source", source);
  console.log("predpred", pred);
  var target = Channel.create(undefined);
  console.log("target", target);
  Channel.listen(source, (function (m) {
          if (Curry._1(pred, m)) {
            Channel.send(target, m);
            return ;
          }
          
        }));
  return Channel.to_read_only(target);
}

var chan = Channel.create(undefined);

var test = John.make(1, 2, undefined);

Channel.listen(filter(chan, (function (i) {
            return i.b > 0;
          })), (function (i) {
        console.log("i>0", i.b);
        
      }));

Channel.send(chan, test);

exports.end$prime = end$prime;
exports.filter = filter;
exports.chan = chan;
exports.test = test;
/* chan Not a pure module */
