// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Channel = require("./Channel.bs.js");

var chan = Channel.create(undefined);

Channel.send(chan, 5);

var msg = Channel.recv_sync(chan);

if (msg !== undefined) {
  console.log(" Do something with m. ", msg);
} else {
  console.log(" Handle the no message case. ");
}

Channel.recv(chan, (function (x) {
        console.log(x + 5 | 0);
        
      }));

var msg$1 = Channel.recv_sync(chan);

if (msg$1 !== undefined) {
  console.log(" Do something with m. ", msg$1);
} else {
  console.log(" Handle the no message case. ");
}

exports.chan = chan;
exports.msg = msg$1;
/* chan Not a pure module */
