// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(aOpt, bOpt, param) {
  var a = aOpt !== undefined ? aOpt : 1;
  var b = bOpt !== undefined ? bOpt : 2;
  return {
          a: a,
          b: b
        };
}

var test = make(1, 2, undefined);

console.log(test);

exports.make = make;
exports.test = test;
/* test Not a pure module */
